version: '2'
services:
  graphql-server: 
    build:
      context: ./graphql-server
    volumes:
      - ./graphql-server:/app
      - /app/node_modules
    ports:
      - '4000:4000'
    environment:
      - APP_SERVER_PORT=4000
    depends_on:
      - postgres
    command: npm run dev
    networks:
      - default

  game-app: 
    build:
      context: ./game-app
    volumes:
      - ./game-app:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    environment:
      - APP_SERVER_PORT=3000
    depends_on:
      - graphql-server
    command: npm run dev
    networks:
      - default

  postgres:
    image: postgres
    restart: always
    env_file:
      - ./graphql-server/database.env 
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - default